### ISSUE TITLE
error reading rebecca-martin.md

### ISSUE THREAD

**Issue by zhangsj96** [UNLV-SPFG/UNLV-SPFG.github.io#23]
```bash
Error: YAML Exception reading /Users/shjzhang/github/UNLV-SPFG.github.io/_team/rebecca-martin.md: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 11 column 11
```

**Comment by hbaehr** [comment]
There is a missing double quotation mark that should go at the end of the line below
```
<li> Planetary and solar system dynamics"
```
that I missed in review.

**Comment by sabaronett** [comment]
Good catch, @hbaehr. This is actually related to [what I just mentioned](https://github.com/UNLV-SPFG/UNLV-SPFG.github.io/issues/21#issuecomment-1033234343) to @DavidRRice in #21.

**Comment by hbaehr** [comment]
Resolved.
