### ISSUE TITLE
Add URL to ReadMe

### ISSUE THREAD

**Issue by DavidRRice** [UNLV-SPFG/UNLV-SPFG.github.io#27]
For new github pages users, it'd be helpful for READMe to state:
The site can be found at <UNLV-SPFG.github.io>.

**Comment by sabaronett** [comment]
I've added the URL to the **About** section (RHS), but feel free to edit [`README.md`](https://github.com/UNLV-SPFG/UNLV-SPFG.github.io/blob/dev/README.md) and submit a PR.

Also, please label issues like these as **documentation**.

**Comment by sabaronett** [comment]
P.S.: please link your PR to this issue (under **Linked pull requests** on RHS of this page).
